server:
  port: 0
logging:
  config: classpath:logback-spring.xml
spring:
  application:
    name: Mqtt2Kafka
  mqtt:
    url: tcp://192.168.1.113:1883
    username:
    password:
    client:
      id: ${spring.application.name}
    default_topic: "espiot"
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.113:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}
